const data = {
  products: [
    {
      name: 'Centella Green Level Unscented Sun SPF50+ PA++++',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: 'wardah.png', // 679px × 829px
      price: '$120',
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Centella Green Level Unscented Sun SPF50+ PA++++',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: 'avioskin.png',
      price: '$250',
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Centella Green Level Unscented Sun SPF50+ PA++++',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: 'centella-toner.png',
      price: '$25',
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Centella Green Level Unscented Sun SPF50+ PA++++',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: 'whitelab.png',
      price: '$65',
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Centella Green Level Unscented Sun SPF50+ PA++++',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: 'whitelab.png',
      price: '$65',
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Centella Green Level Unscented Sun SPF50+ PA++++',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: 'whitelab.png',
      price: '$65',
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Centella Green Level Unscented Sun SPF50+ PA++++',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: 'whitelab.png',
      price: '$65',
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Centella Green Level Unscented Sun SPF50+ PA++++',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: 'whitelab.png',
      price: '$65',
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;